SNP="snp"
EFFECT_ALLELE="effect_allele"
NON_EFFECT_ALLELE="non_effect_allele"
ZSCORE="zscore"
CHROMOSOME = "chromosome"
POSITION = "position"
DOSAGES="dosages"
FREQUENCY="frequency"
OR="or"
BETA="beta"
BETA_SIGN="beta_sign"
SE="se"
PVALUE="pvalue"

GENE="gene"
GENE_NAME="gene_name"